spring.application.name=CareTag
jwt.key=0IwxYq/aSlPXDUtIhr5wnKpfHNeEPUgSPX4YRh5POTA=
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Users

server.port=8080
server.address=0.0.0.0
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhishekpillai1350@gmail.com
spring.mail.password=kzww bgem lhjw wgxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.oauth2.client.registration.google.redirect-uri= https://uncatastrophic-nonobserving-marylyn.ngrok-free.dev/login/oauth2/code/google
server.forward-headers-strategy=framework

spring.data.mongodb.auto-index-creation=true
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.web=DEBUG


crpytographic.aes-key=ayjwzUIcBh73K56Kf+vQdG6cWG2WPYiAMXBztHWeFNY=

azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=caretagstorage;AccountKey=0XTPn1C+PIZ1FJ1FiyKRic4robwdN6hHHmnWdB6XiwFv2Lm0qNwVjPlNktH4+rDR9z6CeMFRuUHH+AStFxMeSQ==;EndpointSuffix=core.windows.net
azure.storage.container-name=patientprofile


spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB